#ifndef SHOW_ZH_21X20_H__
#define SHOW_ZH_21X20_H__
extern const unsigned char dtdy[];//单体电压 
extern const unsigned char dtwd[];//单体温度 
extern const unsigned char dcdl[];//电池电流 
extern const unsigned char gydc[];//高压电池 
extern const unsigned char zgdy[];//最高电压 
extern const unsigned char zddy[];//最低电压 
extern const unsigned char zgwd[];//最高温度 
extern const unsigned char zdwd[];//最低温度 
extern const unsigned char djsrdy[];//电机输入电压 
extern const unsigned char djsrdl[];//电机输入电流 
extern const unsigned char djzs[];//电机转速 
extern const unsigned char djzj[];//电机转矩 
extern const unsigned char djkzq[];//电机控制器 
extern const unsigned char djikzq[];//电机控制器 
extern const unsigned char djwd[];//电机温度 
extern const unsigned char xdcdy[];//蓄电池电压 
extern const unsigned char qbmklx[];//前部模块离线 
extern const unsigned char dbmklx[];//顶部模块离线 
extern const unsigned char hbmklx[];//后部模块离线 
extern const unsigned char zmwg[];//中门未关报警 
extern const unsigned char qmwg[];//前门未关报警 
extern const unsigned char xdcdyd[];//蓄电池电压低 
extern const unsigned char chagre[];//正在充电，禁止行车 
extern const unsigned char hcmwg[];//后仓门未关报警 
extern const unsigned char clcs[];//车辆超速 
extern const unsigned char qmwyjfbj[];//前门外应急阀报警 
extern const unsigned char zmwyjfbj[];//中门外应急阀报警 
extern const unsigned char qmnyjfbj[];//前门内应急阀报警 
extern const unsigned char zmnyjfbj[];//中门内应急阀报警 
extern const unsigned char zpl[];//左偏离 
extern const unsigned char ypl[];//右偏离 
extern const unsigned char pzbjyx[];//碰撞预警有效 
extern const unsigned char reserve[];//备用 
extern const unsigned char sjlkbj[];//司机离开报警 
extern const unsigned char bmsgz[];//BMS故障 
extern const unsigned char hsgz[];//互锁故障 
extern const unsigned char wdcybj[];//温度差异报警 
extern const unsigned char dcgwbj[];//电池高温报警 
extern const unsigned char cnxtgybj[];//车载储能装置类型过压报警 
extern const unsigned char cnxtqybj[];//车载储能装置类型欠压报警 
extern const unsigned char socgdbj[];//SOC过低报警 
extern const unsigned char dtdygg[];//单体电压过高 
extern const unsigned char dtdygd[];//单体电压过低 
extern const unsigned char socggbj[];//SOC过高报警 
extern const unsigned char soctbbj[];//SOC跳变报警 
extern const unsigned char cnxtppbj[];//可充电储能系统不匹配报警 
extern const unsigned char dtdycybj[];//电池单体一致性差报警 
extern const unsigned char cnxtgc[];//车载储能装类型过充 
extern const unsigned char dczgygz[];//电池组过压故障 
extern const unsigned char dczqygz[];//电池组欠压故障 
extern const unsigned char dtgygg[];//单体过压故障 
extern const unsigned char dtqygg[];//单体欠压故障 
extern const unsigned char dtdycygz[];//单体电压差异故障 
extern const unsigned char wdcygz[];//温度差异故障 
extern const unsigned char wdggz[];//温度过高故障 
extern const unsigned char wdgdgz[];//温度过低故障 
extern const unsigned char cdglgz[];//充电过流故障 
extern const unsigned char fdglgz[];//放电过流故障 
extern const unsigned char socgggz[];//SOC过高故障 
extern const unsigned char socgdgz[];//SOC过低故障 
extern const unsigned char cdqwdgz[];//充电枪温度故障 
extern const unsigned char dydxgz[];//电压断线故障 
extern const unsigned char wddxgz[];//温度断线故障 
extern const unsigned char nbtxgz[];//内部通讯故障 
extern const unsigned char xtgz[];//系统故障 
extern const unsigned char cantxgz[];//CAN通信故障 
extern const unsigned char jygz[];//绝缘故障 
extern const unsigned char qbdcacgz[];//气泵DCAC故障 
extern const unsigned char ybdcacgz[];//油泵DCAC故障 
extern const unsigned char dldcxtgz[];//动力电池系统故障 
extern const unsigned char djxtgr[];//电机系统过热 
extern const unsigned char djcs[];//电机超速 
extern const unsigned char ktgz[];//空调故障 
extern const unsigned char ycgz[];//预充故障 
extern const unsigned char mkgz[];//模块故障 
extern const unsigned char xdlgz[];//相电流过流 
extern const unsigned char kzqgy[];//控制器过压 
extern const unsigned char zjgz[];//自检故障 
extern const unsigned char dygz[];//低压供电故障 
extern const unsigned char djdzgz[];//电机堵转故障 
extern const unsigned char mxglgz[];//母线过流故障 
extern const unsigned char djkzqgw[];//电机控制器过温 
extern const unsigned char csgz[];//超速故障 
extern const unsigned char kzqqy[];//控制器欠压 
extern const unsigned char djgw[];//电机过温 
extern const unsigned char djgzai[];//电机过载 
extern const unsigned char mkwdbj[];//模块过温告警 
extern const unsigned char djwdbj[];//电机过温告警 
extern const unsigned char mxqybj[];//母线欠压告警 
extern const unsigned char mxgybj[];//母线过压告警 
extern const unsigned char wddkbj[];//温度断线告警 
extern const unsigned char qbsrgl[];//气泵输入过流 
extern const unsigned char qbsrgy[];//气泵输入过压 
extern const unsigned char qbsrqy[];//气泵输入欠压 
extern const unsigned char qbgzbh[];//气泵过载保护 
extern const unsigned char qbsrscdk[];//气泵输入输出断开 
extern const unsigned char qbsrscdl[];//气泵输入输出短路 
extern const unsigned char qbscdl[];//气泵输出缺相 
extern const unsigned char qbkzqgw[];//气泵控制器过温 
extern const unsigned char qbdjcs[];//气泵电机超速 
extern const unsigned char qbdjgw[];//气泵电机过温 
extern const unsigned char ybsrgl[];//油泵输入过流 
extern const unsigned char ybsrgy[];//油泵输入过压 
extern const unsigned char ybsrqy[];//油泵输入欠压 
extern const unsigned char ybgzbh[];//油泵过载保护 
extern const unsigned char ybsrscdk[];//油泵输入输出断开 
extern const unsigned char ybsrscdl[];//油泵输入输出短路 
extern const unsigned char ybscdl[];//油泵输出缺相 
extern const unsigned char ybkzqgw[];//油泵控制器过温 
extern const unsigned char ybdjcs[];//油泵电机超速 
extern const unsigned char ybdjgw[];//油泵电机过温 
extern const unsigned char dcdcxtgz[];//DCDC系统故障 
extern const unsigned char ybxtgz[];//油泵系统故障 
extern const unsigned char qbxtgz[];//气泵系统故障 
extern const unsigned char dldcdk[];//动力电池断开 
extern const unsigned char yisuo[];//已锁 
extern const unsigned char weisuo[];//未锁 
extern const unsigned char zhengchang[];//正常 
extern const unsigned char guzhang[];//故障 
extern const unsigned char gongzuo[];//工作 
extern const unsigned char tingzhi[];//停止 
extern const unsigned char bihe[];//闭合 
extern const unsigned char duankai[];//断开 
extern const unsigned char kailu[];//开路 
extern const unsigned char duanlu[];//短路 
extern const unsigned char kzqwd[];//控制器温度 
extern const unsigned char char_rpm[];//Rpm 
extern const unsigned char char_lh[];//LH 
extern const unsigned char char_mpa[];//Mpa 
extern const unsigned char char_kpa[];//Kpa 
extern const unsigned char char_kwh[];//Kwh 
extern const unsigned char djgzdm[];//电机故障代码 
extern const unsigned char djgzdj[];//电机故障等级 
extern const unsigned char djxtzt[];//电机系统状态 
extern const unsigned char djlife[];//电机Life 
extern const unsigned char zcgzdm[];//整车故障代码 
extern const unsigned char zdtb[];//制动踏板 
extern const unsigned char ymtb[];//油门踏板 
extern const unsigned char km1h[];//km/h 
extern const unsigned char sczt[];//锁车状态 
extern const unsigned char zclife[];//整车Life 
extern const unsigned char xhlc[];//续驶里程 
extern const unsigned char gzgl[];//工作功率 
extern const unsigned char srdy[];//输入电压 
extern const unsigned char srdl[];//输入电流 
extern const unsigned char scdy[];//输出电压 
extern const unsigned char scdl[];//输出电流 
extern const unsigned char kzqyczt[];//控制器预充状态 
extern const unsigned char ywc[];//已完成 
extern const unsigned char wwc[];//未完成 
extern const unsigned char dcdczt[];//DCDC状态 
extern const unsigned char gzdm[];//故障代码 
extern const unsigned char dcdclife[];//DCDCLife 
extern const unsigned char qbzt[];//气泵状态 
extern const unsigned char qblife[];//气泵Life 
extern const unsigned char ybzt[];//油泵状态 
extern const unsigned char yblife[];//油泵Life 
extern const unsigned char bmsgzdj[];//BMS故障等级 
extern const unsigned char dcxtnz[];//电池系统内阻 
extern const unsigned char cfdms[];//充放电模式 
extern const unsigned char dczt[];//电池状态 
extern const unsigned char zzjcqzt[];//总正接触器状态 
extern const unsigned char gyjcqzt[];//高压接触器状态 
extern const unsigned char zfjcqzt[];//总负接触器状态 
extern const unsigned char ycjcqzt[];//预充接触器状态 
extern const unsigned char cdjcqzt[];//充电接触器状态 
extern const unsigned char dcjrxtgzzt[];//电池加热系统工作状态 
extern const unsigned char dclqxtgzzt[];//电池冷却系统工作状态 
extern const unsigned char dczzdy[];//电池组总电压 
extern const unsigned char dczzdl[];//电池组总电流 
extern const unsigned char dczscdy[];//电池组输出电压 
extern const unsigned char zdyxfddl[];//最大允许放电电流 
extern const unsigned char zdyxcddl[];//最大允许充电电流 
extern const unsigned char dczyxzgwd[];//电池组允许最高温度 
extern const unsigned char dczyxzdwd[];//电池组允许最低温度 
extern const unsigned char dczyxzdsoc[];//电池组允许最低SOC 
extern const unsigned char dczsynl[];//电池组剩余能量 
extern const unsigned char pjwd[];//平均温度 
extern const unsigned char zlcdqzjwd[];//直流充电枪正极温度 
extern const unsigned char zlcdqfjwd[];//直流充电枪负极温度 
extern const unsigned char jlcdqwd[];//交流充电枪温度 
extern const unsigned char jydz[];//绝缘电阻 
extern const unsigned char cdcnxtsl[];//充电储能子系统数量 
extern const unsigned char cdcnxth[];//充电储能子系统号 
extern const unsigned char dtdcsl[];//单体电池总数 
extern const unsigned char cdcnwdsl[];//充电储能温度数量 
extern const unsigned char cdcnxtgzsl[];//充电储能系统故障数量 
extern const unsigned char kom[];//kΩ 
extern const unsigned char xh1[];//信号1 
extern const unsigned char xh2[];//信号2 
extern const unsigned char bbh[];//版本号 
extern const unsigned char dzxz1[];//地址选择1 
extern const unsigned char dzxz2[];//地址选择2 
extern const unsigned char cantx[];//CAN通讯 
extern const unsigned char zzxkg[];//左转向开关 
extern const unsigned char yzxkg[];//右转向开关 
extern const unsigned char xdkg[];//小灯开关 
extern const unsigned char ygdkg[];//远光灯开关 
extern const unsigned char jgdkg[];//近光灯开关 
extern const unsigned char qwdkg[];//前雾灯开关 
extern const unsigned char hwdkg[];//后雾灯开关 
extern const unsigned char sjdkg[];//司机灯开关 
extern const unsigned char ctd1kg[];//长条灯1开关 
extern const unsigned char dskg[];//电视开关 
extern const unsigned char ygddkg[];//雨刮低档开关 
extern const unsigned char ygjxdkg[];//雨刮间歇档开关 
extern const unsigned char yggdkg[];//雨刮高档开关 
extern const unsigned char ygpsdkg[];//雨刮喷水开关 
extern const unsigned char dlbkg[];//电喇叭开关 
extern const unsigned char aqdbj[];//安全带报警 
extern const unsigned char zlbj[];//驾驶员离开信号 
extern const unsigned char absgzzs[];//ABS工作指示灯 
extern const unsigned char qmkkg[];//前门开开关 
extern const unsigned char qmgkg[];//前门关开关 
extern const unsigned char zmkkg[];//中门开开关 
extern const unsigned char zmgkg[];//中门关开关 
extern const unsigned char ctd2kg[];//长条灯2开关 
extern const unsigned char pqsjqkg[];//排气扇进气开关 
extern const unsigned char pqspqkg[];//排气扇排气开关 
extern const unsigned char wxbjkg[];//危险报警开关 
extern const unsigned char cdhx[];//充电唤醒 
extern const unsigned char onhx[];//ON档唤醒 
extern const unsigned char mnxh1[];//模拟信号1 
extern const unsigned char mnxh2[];//模拟信号2 
extern const unsigned char mnxh3[];//模拟信号3 
extern const unsigned char mnxh4[];//模拟信号4 
extern const unsigned char mnxh5[];//模拟信号5 
extern const unsigned char mnxh6[];//模拟信号6 
extern const unsigned char zmkxh[];//中门开信号 
extern const unsigned char zqmcp[];//左前摩擦片 
extern const unsigned char yqmcp[];//右前摩擦片 
extern const unsigned char zdkg[];//制动开关 
extern const unsigned char sjfskg[];//司机风扇 
extern const unsigned char mlkg[];//门铃开关 
extern const unsigned char add[];//Add 
extern const unsigned char qmkxh[];//前门开信号 
extern const unsigned char zczdkg[];//驻车制动开关 
extern const unsigned char swbj[];//水位传感器开关 
extern const unsigned char hcmkg[];//后仓门开关 
extern const unsigned char ygdddj[];//雨刮低档电机 
extern const unsigned char yggddj[];//雨刮高档电机 
extern const unsigned char ygpsdj[];//雨刮喷水电机 
extern const unsigned char ktdy[];//空调电源 
extern const unsigned char zzxd[];//左转向灯 
extern const unsigned char zygd[];//左远光灯 
extern const unsigned char yygxd[];//右远光灯 
extern const unsigned char zjgd[];//左近光灯 
extern const unsigned char yjgd[];//右近光灯 
extern const unsigned char zqwd[];//左前雾灯 
extern const unsigned char yzxd[];//右转向灯 
extern const unsigned char dysc[];//投币机翻板信号输出 
extern const unsigned char yqwd[];//右前雾灯 
extern const unsigned char qmd[];//前门踏步灯 
extern const unsigned char wzd[];//位置灯 
extern const unsigned char ctd1[];//长条灯1 
extern const unsigned char sjd[];//司机灯 
extern const unsigned char qmksc[];//前门开门电磁阀 
extern const unsigned char qmgsc[];//前门关门电磁阀 
extern const unsigned char zmksc[];//中门开门电磁阀 
extern const unsigned char zmgsc[];//中门关门电磁阀 
extern const unsigned char dssc[];//电视输出 
extern const unsigned char zdd[];//制动灯 
extern const unsigned char ctd2[];//长条灯2 
extern const unsigned char sjfs[];//司机风扇 
extern const unsigned char mdy[];//门泵电源 
extern const unsigned char hwd[];//后雾灯 
extern const unsigned char dcd1[];//倒车灯1 
extern const unsigned char hmd[];//中门踏步灯 
extern const unsigned char dcd2[];//倒车灯2 
extern const unsigned char lqdy[];//冷凝器电源 
extern const unsigned char qydy[];//气压传感器电源 
extern const unsigned char dlb1[];//电喇叭1 
extern const unsigned char dlb2[];//电喇叭2 
extern const unsigned char dclb[];//倒车喇叭 
extern const unsigned char cssb[];//车速速比 
extern const unsigned char sbsz[];//速比设置 
extern const unsigned char lcsz[];//里程设置 
extern const unsigned char zjlc[];//总计里程 
extern const unsigned char sb[];//速比 
extern const unsigned char chesu[];//车速 
extern const unsigned char tc[];//退出 
extern const unsigned char zj[];//总计 
#endif